/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.termin;

import domen.Rezultat;
import domen.TerminTestiranja;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;

import kontroler.Kontroler;
import model.ModelTabeleRezultat;

/**
 *
 * @author Dule Djo
 */
public class SviRezultatiForma extends javax.swing.JDialog {

	/**
	 * Creates new form SviRezultatiForma
	 */
	public SviRezultatiForma(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		srediTabelu();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		pnlResults = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblRezultati = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		pnlResults.setBackground(new java.awt.Color(255, 255, 255));
		pnlResults.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Izvestaj svih rezultata",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 0, 15))); // NOI18N

		tblRezultati.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		tblRezultati
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(tblRezultati);

		javax.swing.GroupLayout pnlResultsLayout = new javax.swing.GroupLayout(pnlResults);
		pnlResults.setLayout(pnlResultsLayout);
		pnlResultsLayout
				.setHorizontalGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlResultsLayout.createSequentialGroup().addContainerGap()
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
								.addContainerGap()));
		pnlResultsLayout
				.setVerticalGroup(
						pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(pnlResultsLayout.createSequentialGroup().addGap(52, 52, 52)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(34, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addComponent(pnlResults,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(pnlResults, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SviRezultatiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SviRezultatiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SviRezultatiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SviRezultatiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                SviRezultatiForma dialog = new SviRezultatiForma(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JPanel pnlResults;
	private javax.swing.JTable tblRezultati;
	// End of variables declaration//GEN-END:variables

	private void srediTabelu() {
		ModelTabeleRezultat modelTabeleRezultat = new ModelTabeleRezultat(new ArrayList<Rezultat>());
		// dodaj rezultate ovde
		try {
			List<Rezultat> list = Kontroler.getInstance().dajSveRezultate();

			Gson gson = new GsonBuilder().setPrettyPrinting().create();
//			JsonArray myCustomArray = gson.toJsonTree(list).getAsJsonArray();
			try (PrintWriter out = new PrintWriter(new FileWriter("results.json"))) {

				out.print(gson.toJson(list));
			} catch (IOException e) {
				e.printStackTrace();
			}
			for (Rezultat r : list) {
				modelTabeleRezultat.addRezultat(r);
			}
		} catch (Exception ex) {
			Logger.getLogger(RezultatForma.class.getName()).log(Level.SEVERE, null, ex);
		}
		tblRezultati.setModel(modelTabeleRezultat);
	}
}
