/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.termin;

import kontroler.Kontroler;
import domen.Laborant;
import domen.Pacijent;
import domen.TerminTestiranja;
import domen.Test;
import gui.GlavnaForma;
import gui.ModPretraga;
import gui.PretragaForma;
import java.awt.Color;
import java.awt.Frame;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.ParseException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DuleDjo
 */
public class TerminForma extends javax.swing.JDialog {

    private boolean inicijalizovana;
    private Pacijent odabraniPacijent;

    /**
     * Creates new form FrmExam
     */
    public TerminForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediFormu();
        popuniKomboPacijenata();
        popuniKomboLaboranata();
        setTitle("Zakazivanje termina za testiranje na određeni dan");
        setLocationRelativeTo(null);
        inicijalizovana = true;
        lblNemaLaboranata.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbLaboranti = new javax.swing.JComboBox<>();
        cbPacijenti = new javax.swing.JComboBox<>();
        btnSacuvajTermin = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        lblNemaLaboranata = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNapomena = new javax.swing.JTextField();
        btnPretraziPacijente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Zakažite termin:  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Datum: (dd.mm.gggg.)");

        txtDatum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDatum.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Napomena:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Pacijent koji će se testirati:");

        cbLaboranti.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbLaboranti.setModel(new javax.swing.DefaultComboBoxModel<>(new Object[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLaboranti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLaborantiActionPerformed(evt);
            }
        });

        cbPacijenti.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbPacijenti.setModel(new javax.swing.DefaultComboBoxModel<>(new Object[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPacijenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPacijentiActionPerformed(evt);
            }
        });

        btnSacuvajTermin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSacuvajTermin.setText("Zakaži termin");
        btnSacuvajTermin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajTerminActionPerformed(evt);
            }
        });

        lblNemaLaboranata.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNemaLaboranata.setForeground(new java.awt.Color(255, 0, 0));
        lblNemaLaboranata.setText("Trenutno nema laboranata za izabrani test!");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Laborant koji će raditi testiranje:");

        txtNapomena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNapomena.setToolTipText("");

        btnPretraziPacijente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPretraziPacijente.setText("Pretrazi");
        btnPretraziPacijente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziPacijenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSacuvajTermin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNemaLaboranata)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDatum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtNapomena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbLaboranti, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(326, 326, 326)
                                .addComponent(cbPacijenti, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPretraziPacijente)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(cbPacijenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziPacijente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(cbLaboranti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNapomena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lblNemaLaboranata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnSacuvajTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Termin testiranja za određeni test:  ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajTerminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajTerminActionPerformed
        try {
            if (txtDatum.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!");
                return;
            }
            Date datum = null;
            try {
                datum = Kontroler.getInstance().getSdf().parse(txtDatum.getText().trim());
                lblError.setText("");
            } catch (ParseException ex) {
                Logger.getLogger(TerminForma.class.getName()).log(Level.SEVERE, null, ex);
                lblError.setForeground(Color.red);
                lblError.setText("Unesite datum u formatu dd.mm.gggg");
                return;
            }
            Laborant la = (Laborant) cbLaboranti.getSelectedItem();
            Pacijent pacijent = (Pacijent) cbPacijenti.getSelectedItem();
            String napomena = txtNapomena.getText();
            if(napomena.isEmpty()){
                napomena = "";
            }

            TerminTestiranja t = new TerminTestiranja(Long.MAX_VALUE, datum, napomena, pacijent,la);
            Kontroler.getInstance().sacuvajTerminTestiranja(t);
            int option = JOptionPane.showConfirmDialog(this, "Termin je uspešno zakazan! Da li želite da zakazete jos neki termin?", "", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                txtDatum.setText("");
            } else {
                this.dispose();
            }
        } catch (Exception ex) {
            Logger.getLogger(TerminForma.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnSacuvajTerminActionPerformed

    private void cbLaborantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLaborantiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLaborantiActionPerformed

    private void cbPacijentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPacijentiActionPerformed
        lblNemaLaboranata.setVisible(false);
//        System.out.println("event cbTest: init="+inicijalizovana);
//        if (inicijalizovana) {
//            filtrirajComboLaboranata();
//        }
    }//GEN-LAST:event_cbPacijentiActionPerformed

    private void btnPretraziPacijenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziPacijenteActionPerformed
        // TODO add your handling code here:
        new PretragaForma((GlavnaForma) this.getParent(), true, ModPretraga.TERMIN).setVisible(true);
        popuniKomboPacijenata();
    }//GEN-LAST:event_btnPretraziPacijenteActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        popuniKomboPacijenata();
    }//GEN-LAST:event_formMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretraziPacijente;
    private javax.swing.JButton btnSacuvajTermin;
    private javax.swing.JComboBox<Object> cbLaboranti;
    private javax.swing.JComboBox<Object> cbPacijenti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblNemaLaboranata;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtNapomena;
    // End of variables declaration//GEN-END:variables

    private void popuniKomboLaboranata() {
        cbLaboranti.removeAllItems();
        try {
            List<Laborant> list = Kontroler.getInstance().dajSveLaborante();
            for (Laborant l : list) {
                cbLaboranti.addItem(l);
            }
        } catch (Exception ex) {
            Logger.getLogger(TerminForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        popuniKomboPacijenata();
    }

    private void popuniKomboPacijenata() {
        if((Pacijent) session.Session.getInstance().getUseCaseParams().get("izabranipacijent")!= null){
            cbPacijenti.setSelectedItem((Pacijent) session.Session.getInstance().getUseCaseParams().get("izabranipacijent"));
            return;
        }
        cbPacijenti.removeAllItems();
        try {
            List<Pacijent> list = Kontroler.getInstance().dajSvePacijente();
            for (Pacijent p : list) {
                cbPacijenti.addItem(p);
            }
        } catch (Exception ex) {
            Logger.getLogger(TerminForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void srediFormu() {
        txtDatum.setForeground(Color.GRAY);
        txtDatum.setText("Na primer 28.10.2020");
        txtDatum.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txtDatum.getText().equals("Na primer 28.10.2020")) {
                    txtDatum.setText("");
                    txtDatum.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (txtDatum.getText().isEmpty()) {
                    txtDatum.setForeground(Color.GRAY);
                    txtDatum.setText("Na primer 28.10.2020");
                }
            }
        });
    }
    

//    private void filtrirajComboLaboranata() {
//        // u kombu laboranata zadrzi samo one laborante koji testiraju datim testom - to je bila ideja ove metode!
//        cbLaboranti.removeAllItems();
//        try {
//            Test test = (Test) cbPacijenti.getSelectedItem();
//            System.out.println(test);
//            System.out.println(test.getTestID());
//            List<Laborant> list = Kontroler.getInstance().dajSveLaborante();
//            for (Laborant l : list) {
//                System.out.println(l);
//                System.out.println(l.getTest().getTestID());                
//                if (l.getTest().equals(test)) {
//                    cbLaboranti.addItem(l);
//                }
//            }
//            System.out.println(cbLaboranti.getItemCount());
//            if (cbLaboranti.getItemCount() == 0) {
//                lblNemaLaboranata.setVisible(true);
//            }
//        } catch (Exception ex) {
//            Logger.getLogger(RezultatForma.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }

    public Pacijent getOdabraniPacijent() {
        return odabraniPacijent;
    }

    public void setOdabraniPacijent(Pacijent odabraniPacijent) {
        this.odabraniPacijent = odabraniPacijent;
    }
}
